#!/usr/bin/env python3
"""Re-test H1/H2 (docs/action_space_v3_formulation.md §5, §7 step 2) on the naive-prompted
action_space_v3 rollouts (policy=action_space_llm).

For every AI turn in every saved rollout JSONL, reconstructs:
  - control       : EXTEND/RECOMMEND, recovered from `selected_action`. Rollouts collected before
                    action_space_v3.yaml dropped its McBurney locution/type sublayer store this as
                    "INFORM.ask_justify"/"RECOMMEND.move" (dot-separated); rollouts collected after
                    store the bare control id ("EXTEND"/"RECOMMEND", no dot). `_control_map` below
                    handles both -- see plugins/policy/action_space_llm_policy.py's docstring.
  - D_t           : 1 - b^H_t(y_hat^A_t), the doctor's PRE-turn belief_dist on the option the AI's
                    free-text belief this turn maps onto. The map from free text -> lettered option
                    is a simple word-overlap heuristic (no extra LLM/API calls) -- an approximation,
                    not a judge call.
  - burden dims   : the following user turn's self-reported NASA-TLX overall + per-dimension
                    (mental_demand, performance, effort, frustration) burden, i.e. the burden
                    generated BY this AI turn. Rows with cognitive_burden_n_ok == 0 (burden-judge
                    parse failure, neutral-3 fallback) are kept in records.csv but excluded from
                    every mean below.

Category split (the H1 test): RECOMMEND is split by belief-alignment D_t into
RECOMMEND_aligned (D_t < 0.5) and RECOMMEND_misaligned (D_t >= 0.5); EXTEND is pooled as one
category (it never discloses a conclusion, so alignment doesn't apply -- consistent with H2).
RECOMMEND turns whose AI belief can't be mapped to an option are excluded from the category
deliverables (counted in metrics.csv as recommend_unmapped_n).

Always persists results to disk under --out-dir:
  - records.csv                     : one row per extracted AI turn, all raw fields + n_ok flag.
  - metrics.csv                     : n per category, RECOMMEND misaligned fraction, unmapped count.
  - persona_burden_trend.csv/.png   : mean overall burden by persona x turn index.
  - category_burden_means.csv/.png  : mean overall burden by category (EXTEND / RECOMMEND_aligned /
                                       RECOMMEND_misaligned) -- the H1 test.
  - category_dim_means.csv/.png     : mean of each NASA-TLX item by category -- the H1-vs-H2
                                       mechanism check (frustration -> conflict, mental_demand/
                                       effort -> load).
Terminal output is a convenience preview only -- the CSV/PNG are the actual record of the run.

Usage:
    python scripts/analyze_action_space_v3_burden.py \
        --glob "outputs/poc_action_v3_naive_postmerge/*/rollouts/*.jsonl" \
        --out-dir outputs/action_space_v3_burden_analysis_postmerge
"""
from __future__ import annotations

import argparse
import csv
import glob
import json
import re
import statistics
import sys
from pathlib import Path

_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_ROOT))

from core.config import load_action_space

_STOPWORDS = {
    "a", "an", "the", "of", "and", "or", "with", "in", "to", "is", "are", "for", "on", "at",
    "by", "as", "from", "this", "that", "likely", "most", "consistent", "given", "due",
}

_TLX_DIMS = ["mental_demand", "performance", "effort", "frustration"]
_TLX_DIMS_NO_FRUSTRATION = ["mental_demand", "performance", "effort"]
_CATEGORIES = ["EXTEND", "RECOMMEND_aligned", "RECOMMEND_misaligned"]
_PLOT_CATEGORY_ORDER = ["RECOMMEND_aligned", "RECOMMEND_misaligned", "EXTEND"]
_CATEGORY_LABELS = {
    "RECOMMEND_aligned": "RECOMMEND\naligned",
    "RECOMMEND_misaligned": "RECOMMEND\nmisaligned",
    "EXTEND": "EXTEND",
}
_DIM_LABELS = {
    "mental_demand": "Mental",
    "performance": "Performance",
    "effort": "Effort",
    "frustration": "Frustration",
}


def _words(text: str) -> set[str]:
    return {w for w in re.findall(r"[a-z]+", text.lower()) if w not in _STOPWORDS and len(w) > 2}


def _map_belief_to_letter(belief_text: str | None, options: dict[str, str]) -> str | None:
    """Word-overlap heuristic: pick the option whose text shares the most content words with
    the AI's free-text belief; None if there's no overlap with any option (unmapped)."""
    if not belief_text:
        return None
    belief_words = _words(belief_text)
    if not belief_words:
        return None
    best_letter, best_score = None, 0
    for letter, text in options.items():
        score = len(belief_words & _words(text))
        if score > best_score:
            best_letter, best_score = letter, score
    return best_letter


def _control_map(action_space_path: str) -> dict[str, str]:
    """cid -> cid (identity; matches action_space_v3.yaml's current no-shim spec, whose
    `selected_action` is the bare control id) plus any `realizes` entries the loaded spec still
    declares (older McBurney-compatible specs), plus a hardcoded bridge for rollouts collected
    under v3.yaml's retired McBurney sublayer (INFORM->EXTEND) so that already-collected data
    (outputs/poc_action_v3_naive/*) keeps parsing after the shim was dropped from the YAML."""
    action_space = load_action_space(action_space_path)
    out: dict[str, str] = {}
    for cid, info in action_space["stages"].items():
        out[cid.upper()] = cid
        for mcb in (info.get("realizes") or []):
            out[str(mcb).upper()] = cid
    out.setdefault("INFORM", "EXTEND")
    return out


def _category(control: str, d_t: float | None) -> str | None:
    if control == "EXTEND":
        return "EXTEND"
    if control == "RECOMMEND":
        if d_t is None:
            return None
        return "RECOMMEND_misaligned" if d_t >= 0.5 else "RECOMMEND_aligned"
    return None


def extract_records(paths: list[Path], control_map: dict[str, str]) -> list[dict]:
    records: list[dict] = []
    for path in paths:
        persona = path.parent.parent.name  # outputs/<exp>/<persona>/rollouts/<case>.jsonl
        try:
            lines = path.read_text().splitlines()
        except OSError:
            continue
        for line in lines:
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            action = d.get("selected_action") or ""
            if not action:
                continue
            mcb_stage = action.split(".")[0].upper()
            control = control_map.get(mcb_stage)
            if control is None:
                continue
            turns = d.get("dialogue_history") or []
            if len(turns) < 3:
                continue
            medical_turn, prior_user_turn, next_user_turn = turns[-2], turns[-3], turns[-1]
            if medical_turn.get("speaker") != "medical" or next_user_turn.get("speaker") != "user":
                continue
            options = (d.get("case_info") or {}).get("options") or {}
            belief_text = (medical_turn.get("metadata") or {}).get("belief")
            ai_letter = _map_belief_to_letter(belief_text, options)
            prior_belief_dist = (prior_user_turn.get("user_state") or {}).get("belief_dist") or {}
            next_state = next_user_turn.get("user_state") or {}
            burden = next_state.get("cognitive_burden")
            if burden is None:
                continue
            d_t = None
            if ai_letter is not None and prior_belief_dist:
                d_t = 1.0 - float(prior_belief_dist.get(ai_letter, 0.0))
            dims = next_state.get("cognitive_burden_dims") or {}
            records.append({
                "case_id": d.get("case_id"),
                "persona": persona,
                "turn_id": d.get("turn_id"),
                "control": control,
                "action": action,
                "ai_letter": ai_letter,
                "correct_option": (d.get("case_info") or {}).get("correct_option"),
                "d_t": d_t,
                "category": _category(control, d_t),
                "burden": burden,
                "mental_demand": dims.get("mental_demand"),
                "performance": dims.get("performance"),
                "effort": dims.get("effort"),
                "frustration": dims.get("frustration"),
                "n_ok": next_state.get("cognitive_burden_n_ok"),
            })
    return records


def valid_records(records: list[dict]) -> list[dict]:
    """Records usable for any mean: burden-judge actually parsed at least one sample
    (excludes the neutral-3 fallback rows, kept in records.csv but not in any average)."""
    return [r for r in records if (r.get("n_ok") or 0) > 0]


def _mean(xs: list[float]) -> float | None:
    xs = [x for x in xs if x is not None]
    return round(statistics.mean(xs), 3) if xs else None


def _min(xs: list[float]) -> float | None:
    xs = [x for x in xs if x is not None]
    return round(min(xs), 3) if xs else None


def _max(xs: list[float]) -> float | None:
    xs = [x for x in xs if x is not None]
    return round(max(xs), 3) if xs else None


def compute_metrics(records: list[dict]) -> dict:
    ok = valid_records(records)
    recommend = [r for r in ok if r["control"] == "RECOMMEND"]
    mapped_recommend = [r for r in recommend if r["d_t"] is not None]
    misaligned = [r for r in mapped_recommend if r["d_t"] >= 0.5]
    return {
        "total_turns": len(records),
        "fallback_excluded": len(records) - len(ok),
        "extend_n": sum(1 for r in ok if r["category"] == "EXTEND"),
        "recommend_aligned_n": sum(1 for r in ok if r["category"] == "RECOMMEND_aligned"),
        "recommend_misaligned_n": sum(1 for r in ok if r["category"] == "RECOMMEND_misaligned"),
        "recommend_unmapped_n": len(recommend) - len(mapped_recommend),
        "recommend_misaligned_fraction": (
            round(len(misaligned) / len(mapped_recommend), 3) if mapped_recommend else None
        ),
    }


def persona_burden_trend(records: list[dict]) -> list[dict]:
    """One row per (persona, turn_id): mean overall burden + n."""
    ok = [r for r in valid_records(records) if r.get("turn_id") is not None]
    keys = sorted({(r["persona"], r["turn_id"]) for r in ok}, key=lambda k: (k[0], k[1]))
    rows = []
    for persona, turn_id in keys:
        vals = [r["burden"] for r in ok if r["persona"] == persona and r["turn_id"] == turn_id]
        rows.append({"persona": persona, "turn_id": turn_id, "mean_burden": _mean(vals), "n": len(vals)})
    return rows


def category_burden_means(records: list[dict]) -> list[dict]:
    """The H1 test: mean overall burden for EXTEND / RECOMMEND_aligned / RECOMMEND_misaligned."""
    ok = valid_records(records)
    rows = []
    for cat in _CATEGORIES:
        crows = [r for r in ok if r["category"] == cat]
        vals = [r["burden"] for r in crows]
        rows.append({
            "category": cat,
            "n": len(crows),
            "mean_burden": _mean(vals),
            "min_burden": _min(vals),
            "max_burden": _max(vals),
        })
    return rows


def category_burden_means_no_frustration(records: list[dict]) -> list[dict]:
    """Post-hoc sensitivity check: same categories, but overall is recomputed from only
    mental_demand/performance/effort, excluding frustration without changing the runtime judge."""
    ok = valid_records(records)
    rows = []
    for cat in _CATEGORIES:
        crows = [r for r in ok if r["category"] == cat]
        row_means = []
        for r in crows:
            vals = [r.get(dim) for dim in _TLX_DIMS_NO_FRUSTRATION]
            if all(v is not None for v in vals):
                row_means.append(sum(float(v) for v in vals) / len(vals))
        rows.append({
            "category": cat,
            "n": len(crows),
            "mean_burden": _mean(row_means),
            "min_burden": _min(row_means),
            "max_burden": _max(row_means),
        })
    return rows


def category_dim_means(records: list[dict], dims: list[str] | None = None) -> list[dict]:
    """The H1-vs-H2 mechanism check: mean of each NASA-TLX item per category."""
    dims = dims or _TLX_DIMS
    ok = valid_records(records)
    rows = []
    for cat in _CATEGORIES:
        crows = [r for r in ok if r["category"] == cat]
        row = {"category": cat, "n": len(crows)}
        for dim in dims:
            vals = [r[dim] for r in crows]
            row[dim] = _mean(vals)
            row[f"{dim}_min"] = _min(vals)
            row[f"{dim}_max"] = _max(vals)
        rows.append(row)
    return rows


def report(metrics: dict, cat_means: list[dict], dim_means: list[dict]) -> None:
    print(f"\nTotal AI turns extracted: {metrics['total_turns']} "
          f"(fallback-excluded: {metrics['fallback_excluded']})")
    print(f"RECOMMEND misaligned/mapped: {metrics['recommend_misaligned_n']}/"
          f"{metrics['recommend_aligned_n'] + metrics['recommend_misaligned_n']} "
          f"(fraction={metrics['recommend_misaligned_fraction']}), "
          f"unmapped={metrics['recommend_unmapped_n']}")
    print("\n=== Mean burden by category (H1 test) ===")
    for row in cat_means:
        print(f"  {row['category']:<22} n={row['n']:<4} mean_burden={row['mean_burden']}")
    print("\n=== Mean NASA-TLX item by category (H1 vs H2 mechanism) ===")
    print("  " + f"{'category':<22}" + "".join(f"{d:<16}" for d in _TLX_DIMS))
    for row in dim_means:
        print("  " + f"{row['category']:<22}" + "".join(f"{row[d]!s:<16}" for d in _TLX_DIMS))


def write_csv(rows: list[dict], fields: list[str], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows({k: r.get(k) for k in fields} for r in rows)


def plot_persona_trend(rows: list[dict], path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    personas = sorted({r["persona"] for r in rows})
    fig, ax = plt.subplots(figsize=(7, 4.5))
    for persona in personas:
        prows = sorted((r for r in rows if r["persona"] == persona), key=lambda r: r["turn_id"])
        xs = [r["turn_id"] for r in prows if r["mean_burden"] is not None]
        ys = [r["mean_burden"] for r in prows if r["mean_burden"] is not None]
        if xs:
            ax.plot(xs, ys, marker="o", label=persona)
    ax.set_xlabel("turn index")
    ax.set_ylabel("mean burden (NASA-TLX overall, 1-5)")
    ax.set_title("Burden trend by persona")
    ax.legend()
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_category_means(rows: list[dict], path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    by_cat = {r["category"]: r for r in rows}
    fig, ax = plt.subplots(figsize=(6, 4))
    heights = [by_cat[c]["mean_burden"] or 0 for c in _CATEGORIES]
    lower = [
        max(0, (by_cat[c]["mean_burden"] or 0) - (by_cat[c].get("min_burden") or by_cat[c]["mean_burden"] or 0))
        for c in _CATEGORIES
    ]
    upper = [
        max(0, (by_cat[c].get("max_burden") or by_cat[c]["mean_burden"] or 0) - (by_cat[c]["mean_burden"] or 0))
        for c in _CATEGORIES
    ]
    bars = ax.bar(
        _CATEGORIES,
        heights,
        yerr=[lower, upper],
        capsize=5,
        error_kw={"elinewidth": 1.2, "capthick": 1.2},
    )
    for bar, cat in zip(bars, _CATEGORIES):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(),
                 f"n={by_cat[cat]['n']}", ha="center", va="bottom", fontsize=8)
    ax.set_ylabel("mean burden (NASA-TLX overall, 1-5)")
    ax.set_title("H1 test: mean burden by category")
    ax.set_ylim(0, 5.5)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_dim_means(rows: list[dict], path: Path, dims: list[str] | None = None) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    dims = dims or _TLX_DIMS
    by_cat = {r["category"]: r for r in rows}
    x = range(len(dims))
    width = 0.25
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for i, cat in enumerate(_CATEGORIES):
        heights = [by_cat[cat][d] or 0 for d in dims]
        lower = [
            max(0, (by_cat[cat][d] or 0) - (by_cat[cat].get(f"{d}_min") or by_cat[cat][d] or 0))
            for d in dims
        ]
        upper = [
            max(0, (by_cat[cat].get(f"{d}_max") or by_cat[cat][d] or 0) - (by_cat[cat][d] or 0))
            for d in dims
        ]
        offsets = [xi + (i - 1) * width for xi in x]
        ax.bar(
            offsets,
            heights,
            width,
            yerr=[lower, upper],
            capsize=3,
            error_kw={"elinewidth": 1.0, "capthick": 1.0},
            label=f"{cat} (n={by_cat[cat]['n']})",
        )
    ax.set_xticks(list(x))
    ax.set_xticklabels(dims)
    ax.set_ylabel("mean score (1-5)")
    ax.set_title("H1 vs H2 mechanism: NASA-TLX item means by category")
    ax.set_ylim(0, 5.5)
    ax.legend()
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_four_panel_summary(
    cat_rows: list[dict], dim_rows: list[dict], path: Path, dims: list[str] | None = None,
) -> None:
    """Single figure requested for H1/H2 inspection:
    1) overall burden by the three action categories,
    2-4) NASA-TLX item means within each category."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    dims = dims or _TLX_DIMS
    cat_by_name = {r["category"]: r for r in cat_rows}
    dim_by_name = {r["category"]: r for r in dim_rows}
    colors = {
        "RECOMMEND_aligned": "#4C78A8",
        "RECOMMEND_misaligned": "#F58518",
        "EXTEND": "#54A24B",
    }

    fig, axes = plt.subplots(2, 2, figsize=(11, 8), constrained_layout=True)

    ax = axes[0][0]
    heights = [cat_by_name.get(cat, {}).get("mean_burden") or 0 for cat in _PLOT_CATEGORY_ORDER]
    ns = [cat_by_name.get(cat, {}).get("n", 0) for cat in _PLOT_CATEGORY_ORDER]
    lower = [
        max(0, (cat_by_name.get(cat, {}).get("mean_burden") or 0)
            - (cat_by_name.get(cat, {}).get("min_burden") or cat_by_name.get(cat, {}).get("mean_burden") or 0))
        for cat in _PLOT_CATEGORY_ORDER
    ]
    upper = [
        max(0, (cat_by_name.get(cat, {}).get("max_burden") or cat_by_name.get(cat, {}).get("mean_burden") or 0)
            - (cat_by_name.get(cat, {}).get("mean_burden") or 0))
        for cat in _PLOT_CATEGORY_ORDER
    ]
    bars = ax.bar(
        range(len(_PLOT_CATEGORY_ORDER)),
        heights,
        color=[colors[cat] for cat in _PLOT_CATEGORY_ORDER],
        yerr=[lower, upper],
        capsize=5,
        error_kw={"elinewidth": 1.2, "capthick": 1.2},
    )
    ax.set_xticks(range(len(_PLOT_CATEGORY_ORDER)))
    ax.set_xticklabels([_CATEGORY_LABELS[cat] for cat in _PLOT_CATEGORY_ORDER])
    ax.set_ylabel("Mean overall workload (1-5)")
    ax.set_title("Overall Workload")
    ax.set_ylim(0, 5)
    ax.grid(axis="y", alpha=0.25)
    for bar, n, value in zip(bars, ns, heights):
        label = f"{value:.2f}\nn={n}" if value else f"n={n}"
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.06,
                label, ha="center", va="bottom", fontsize=8)

    panel_specs = [
        (axes[0][1], "RECOMMEND_aligned", "RECOMMEND Aligned"),
        (axes[1][0], "RECOMMEND_misaligned", "RECOMMEND Misaligned"),
        (axes[1][1], "EXTEND", "EXTEND"),
    ]
    for dim_ax, cat, title in panel_specs:
        row = dim_by_name.get(cat, {})
        vals = [row.get(dim) or 0 for dim in dims]
        lower = [
            max(0, (row.get(dim) or 0) - (row.get(f"{dim}_min") or row.get(dim) or 0))
            for dim in dims
        ]
        upper = [
            max(0, (row.get(f"{dim}_max") or row.get(dim) or 0) - (row.get(dim) or 0))
            for dim in dims
        ]
        dim_bars = dim_ax.bar(
            range(len(dims)),
            vals,
            color=colors[cat],
            alpha=0.85,
            yerr=[lower, upper],
            capsize=4,
            error_kw={"elinewidth": 1.1, "capthick": 1.1},
        )
        dim_ax.set_xticks(range(len(dims)))
        dim_ax.set_xticklabels([_DIM_LABELS[d] for d in dims], rotation=20, ha="right")
        dim_ax.set_ylabel("Mean item score (1-5)")
        dim_ax.set_title(f"{title} Items (n={row.get('n', 0)})")
        dim_ax.set_ylim(0, 5)
        dim_ax.grid(axis="y", alpha=0.25)
        for bar, value in zip(dim_bars, vals):
            if value:
                dim_ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.06,
                            f"{value:.2f}", ha="center", va="bottom", fontsize=8)

    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--glob", default="outputs/poc_action_v3_naive/*/rollouts/*.jsonl")
    parser.add_argument("--action_space", default="configs/action_space_v3.yaml")
    parser.add_argument("--out-dir", default="outputs/action_space_v3_burden_analysis",
                         help="Directory to persist all CSV/PNG deliverables")
    parser.add_argument("--out", default=None, help="Optional extra path to dump raw records as JSON")
    args = parser.parse_args()

    paths = [Path(p) for p in glob.glob(args.glob)]
    print(f"Found {len(paths)} rollout file(s) matching {args.glob!r}")
    control_map = _control_map(args.action_space)
    records = extract_records(paths, control_map)

    metrics = compute_metrics(records)
    trend_rows = persona_burden_trend(records)
    cat_means = category_burden_means(records)
    cat_means_no_frustration = category_burden_means_no_frustration(records)
    dim_means = category_dim_means(records)
    report(metrics, cat_means, dim_means)

    out_dir = Path(args.out_dir)
    write_csv(records,
              ["case_id", "persona", "turn_id", "control", "action", "ai_letter", "correct_option",
               "d_t", "category", "burden", "mental_demand", "performance", "effort", "frustration",
               "n_ok"],
              out_dir / "records.csv")
    write_csv([metrics], list(metrics.keys()), out_dir / "metrics.csv")
    write_csv(trend_rows, ["persona", "turn_id", "mean_burden", "n"], out_dir / "persona_burden_trend.csv")
    write_csv(cat_means, ["category", "n", "mean_burden", "min_burden", "max_burden"],
              out_dir / "category_burden_means.csv")
    write_csv(cat_means_no_frustration, ["category", "n", "mean_burden", "min_burden", "max_burden"],
              out_dir / "category_burden_means_no_frustration.csv")
    dim_fields = ["category", "n"] + [
        field for dim in _TLX_DIMS for field in (dim, f"{dim}_min", f"{dim}_max")
    ]
    write_csv(dim_means, dim_fields, out_dir / "category_dim_means.csv")

    plot_persona_trend(trend_rows, out_dir / "persona_burden_trend.png")
    plot_category_means(cat_means, out_dir / "category_burden_means.png")
    plot_category_means(cat_means_no_frustration, out_dir / "category_burden_means_no_frustration.png")
    plot_dim_means(dim_means, out_dir / "category_dim_means.png")
    plot_four_panel_summary(cat_means, dim_means, out_dir / "category_four_panel_summary.png")

    print(f"\nPersisted to {out_dir}/: records.csv, metrics.csv, persona_burden_trend.csv/.png, "
          f"category_burden_means.csv/.png, category_burden_means_no_frustration.csv/.png, "
          f"category_dim_means.csv/.png, "
          f"category_four_panel_summary.png")

    if args.out:
        Path(args.out).write_text(json.dumps(records, indent=2, ensure_ascii=False))
        print(f"Raw records also saved to {args.out}")


if __name__ == "__main__":
    main()
