#!/usr/bin/env python3
"""
EXPERIMENTAL one-off: does judging the 5 NASA-TLX dimensions in 5 SEPARATE LLM calls (each
call seeing only that one dimension's rubric, structurally unable to let another dimension's
signal bleed in) recover the oracle ladder's mid-range targets better than the current
single-call burden_judge_system (which asks for all 5 dims at once)?

Reuses the AI utterances ALREADY generated by a prior `verify_load_judge_v3.py` run (read from
its results.json) -- does NOT re-run the generator, only re-judges the same 5 utterances with
the split-call judge, so this only costs the NEW judge calls (5 rungs x 5 dims x samples).

Usage:
    cd /home/kjy/Jaehoon/medical_hac_policy
    conda activate medgym; set -a; source ../.env; set +a; export PYTHONNOUSERSITE=1
    python scripts/compare_split_judge.py \
        --results outputs/verify_load_judge_v3/results.json \
        --judge-model deepseek/deepseek-v3.2 --samples 3
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import statistics
import sys
from pathlib import Path

import yaml
from openai import AsyncOpenAI

_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_ROOT))

from core.json_utils import safe_json_load
from core.token_tracker import tracker
from plugins.user_llm.user_simulator.v3_burden import _TLX_DIMS

def _load_v3_prompts() -> dict:
    """burden_judge_* now lives in prompts/burden_judge.yaml (split out of
    user_simulator_v3.yaml for ease of editing) -- merge both so tmpl[...] lookups stay
    unaffected."""
    with open(_ROOT / "prompts" / "user_simulator_v3.yaml") as f:
        tmpl = yaml.safe_load(f)
    with open(_ROOT / "prompts" / "burden_judge.yaml") as f:
        tmpl.update(yaml.safe_load(f))
    return tmpl


def _load_personas() -> dict:
    personas: dict = {}
    for path in sorted((_ROOT / "source" / "persona").glob("persona_*.yaml")):
        with open(path) as f:
            personas.update(yaml.safe_load(f))
    return personas


def build_single_dim_judge_prompt(
    tmpl: dict, dim: str, scenario: str, persona_instruction: str, dialogue_text: str,
    ai_utterance: str, cumulative_burden: float,
) -> list[dict[str, str]]:
    """Each dimension has its own fully self-contained template pair in
    prompts/user_simulator_v3.yaml (burden_judge_{dim}_system/_user) -- no generic
    {dim_label}/{dim_rubric} placeholder injected from Python here."""
    ctx = dict(
        scenario=scenario, persona_instruction=persona_instruction, dialogue_text=dialogue_text,
        ai_utterance=ai_utterance, cumulative_burden=round(cumulative_burden, 2),
    )
    return [
        {"role": "system", "content": tmpl[f"burden_judge_{dim}_system"].format(**ctx)},
        {"role": "user", "content": tmpl[f"burden_judge_{dim}_user"].format(**ctx)},
    ]


def _parse_single_dim_score(raw: str) -> int | None:
    data = safe_json_load(raw)
    try:
        v = int(round(float(data.get("score"))))
    except (TypeError, ValueError):
        return None
    return max(1, min(5, v))


async def judge_one_dim(
    client: AsyncOpenAI, model: str, max_tokens: int, temperature: float, samples: int, sem: asyncio.Semaphore,
    tmpl: dict, dim: str, scenario: str, persona_instruction: str, dialogue_text: str,
    ai_utterance: str, cumulative_burden: float,
) -> float | None:
    messages = build_single_dim_judge_prompt(
        tmpl, dim, scenario, persona_instruction, dialogue_text, ai_utterance, cumulative_burden,
    )

    async def one() -> int | None:
        async with sem:
            resp = await client.chat.completions.create(
                model=model, messages=messages, temperature=temperature, max_tokens=max_tokens,
                response_format={"type": "json_object"},
            )
        text = resp.choices[0].message.content or ""
        tracker.record(model, messages, text, resp.usage)
        return _parse_single_dim_score(text)

    scores = [s for s in await asyncio.gather(*(one() for _ in range(samples))) if s is not None]
    return round(statistics.mean(scores), 3) if scores else None


async def _run(args) -> None:
    results_path = Path(args.results) if Path(args.results).is_absolute() else _ROOT / args.results
    data = json.loads(results_path.read_text())
    oracle = data["oracle"]
    old_results = oracle["results"]
    old_metrics = oracle["metrics"]
    persona = oracle["persona"]

    scenario = data["scenario"]
    personas = _load_personas()
    persona_instruction = personas[persona]
    tmpl = _load_v3_prompts()

    api_key = os.environ.get("OPENROUTER_API_KEY", "EMPTY")
    client = AsyncOpenAI(api_key=api_key, base_url="https://openrouter.ai/api/v1")
    sem = asyncio.Semaphore(args.concurrency)

    rungs = [r for r in old_results if not r["generation_failed"]]
    print("=== Run parameters ===")
    print(f"  persona      = {persona}  (inherited from {results_path} -- utterances NOT regenerated)")
    print(f"  judge model  = {args.judge_model}  (temperature={args.temperature}, max_tokens={args.max_tokens})")
    print(f"  samples/dim  = {args.samples}")
    print(f"  scenario     = {scenario[:80]}{'...' if len(scenario) > 80 else ''}")
    print(f"Re-judging {len(rungs)} already-generated oracle utterances "
          f"({len(rungs)} rungs x {len(_TLX_DIMS)} dims x {args.samples} samples = "
          f"{len(rungs) * len(_TLX_DIMS) * args.samples} new judge calls)...")

    new_rows = []
    for rung in rungs:
        dim_scores = await asyncio.gather(*(
            judge_one_dim(
                client, args.judge_model, args.max_tokens, args.temperature, args.samples, sem,
                tmpl, dim, scenario, persona_instruction, "[Doctor]: " + data["doctor"],
                rung["ai_utterance"], 0.0,
            )
            for dim in _TLX_DIMS
        ))
        observed = dict(zip(_TLX_DIMS, dim_scores))
        ok_dims = {d: v for d, v in observed.items() if v is not None}
        overall = round(statistics.mean(ok_dims.values()), 3) if len(ok_dims) == len(_TLX_DIMS) else None
        new_rows.append({"id": rung["id"], "level": rung["level"], "target": rung["target"],
                          "observed": observed, "overall_workload_mean": overall})

    # ── Metrics for the split-call judge (same formulas as compute_oracle_metrics) ──
    ok_rows = [r for r in new_rows if r["overall_workload_mean"] is not None]
    per_dim_errors: dict[str, list[float]] = {d: [] for d in _TLX_DIMS}
    for r in ok_rows:
        for d in _TLX_DIMS:
            per_dim_errors[d].append(abs(r["target"][d] - r["observed"][d]))
    new_per_dim_mae = {d: round(statistics.mean(v), 3) for d, v in per_dim_errors.items() if v}
    new_pooled_mae = round(statistics.mean(e for v in per_dim_errors.values() for e in v), 3) if ok_rows else None

    def _spearman(xs: list[float], ys: list[float]) -> float:
        def ranks(v: list[float]) -> list[float]:
            order = sorted(range(len(v)), key=lambda i: v[i])
            r = [0.0] * len(v)
            i = 0
            while i < len(v):
                j = i
                while j + 1 < len(v) and v[order[j + 1]] == v[order[i]]:
                    j += 1
                avg = (i + j) / 2 + 1
                for k in range(i, j + 1):
                    r[order[k]] = avg
                i = j + 1
            return r
        rx, ry = ranks(xs), ranks(ys)
        n = len(xs)
        mx, my = sum(rx) / n, sum(ry) / n
        num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
        den = (sum((a - mx) ** 2 for a in rx) * sum((b - my) ** 2 for b in ry)) ** 0.5
        return round(num / den, 4) if den else 0.0

    new_ordinal = _spearman([r["level"] for r in ok_rows], [r["overall_workload_mean"] for r in ok_rows]) \
        if len(ok_rows) > 1 else 0.0

    # ── Print comparison ──
    print("\n=== Per-rung overall_workload: single-call (old) vs split-call (new) ===")
    old_by_id = {r["id"]: r for r in old_results}
    for r in new_rows:
        old = old_by_id[r["id"]]
        print(f"  {r['id']:<10} target={r['level']}  old={old['overall_workload_mean']:<6}  new={r['overall_workload_mean']}")

    print("\n=== Per-dimension MAE: single-call (old) vs split-call (new) ===")
    for d in _TLX_DIMS:
        print(f"  {d:<16} old={old_metrics['mae']['per_dim'][d]:<6}  new={new_per_dim_mae.get(d)}")

    print(f"\n  pooled MAE   old={old_metrics['mae']['pooled']}  new={new_pooled_mae}")
    print(f"  ordinal rho  old={old_metrics['ordinal']['spearman']}  new={new_ordinal}")
    tracker.print_summary()

    out = {
        "run_params": {
            "persona": persona, "judge_model": args.judge_model, "temperature": args.temperature,
            "max_tokens": args.max_tokens, "samples_per_dim": args.samples, "scenario": scenario,
            "source_results": str(results_path),
        },
        "old_metrics": old_metrics, "new_metrics": {
            "ordinal": {"spearman": new_ordinal}, "mae": {"per_dim": new_per_dim_mae, "pooled": new_pooled_mae},
        },
        "new_results": new_rows,
    }
    out_path = results_path.parent / "split_judge_comparison.json"
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False))
    print(f"\nSaved comparison to {out_path}")

    tracker.accumulate_to_ledger(
        _ROOT / "token_usage_ledger.json",
        run_meta={"script": "compare_split_judge", "n_rungs": len(rungs), "model": args.judge_model},
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", default="outputs/verify_load_judge_v3/results.json")
    parser.add_argument("--judge-model", default="deepseek/deepseek-v3.2")
    parser.add_argument("--max-tokens", type=int, default=200)
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--samples", type=int, default=3)
    parser.add_argument("--concurrency", type=int, default=8)
    args = parser.parse_args()
    asyncio.run(_run(args))


if __name__ == "__main__":
    main()
